on:
  push:
    branches:
    - main
  workflow_dispatch: {}

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  REPO: docker.io/alexeldeib

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build image
      run: |
        set -eux
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        TAG=$(date -Ihours | tr :+ -)
        echo "TAG: ${TAG}"
        docker build --platform linux/amd64 -f images/server/Dockerfile . -t ${REPO}/server:${TAG}
        docker build --platform linux/amd64 -f images/proxy/Dockerfile . -t ${REPO}/proxy:${TAG}
        docker push ${REPO}/server:${TAG}
        docker push ${REPO}/proxy:${TAG}
